
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sai Swapna
 */
public class BuildPizza extends javax.swing.JFrame {

    /**
     * Creates new form BuildPizza
     */
    String size;
    String crust;
    String sauce;
    DbConnection dbc;
    public BuildPizza() throws SQLException, ClassNotFoundException {
        initComponents();
        dbc = new DbConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Light = new javax.swing.JComboBox<>();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sai Swapna\\Downloads\\imageedit_3_4363427810.jpg")); // NOI18N

        jTabbedPane1.setForeground(new java.awt.Color(255, 51, 0));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Choose Cheese And Sauce :-");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(136, 28, 327, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("Cheese?");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(115, 86, 65, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("Choose Your Sauce");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(285, 86, 152, 22);

        Light.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Light.setForeground(new java.awt.Color(255, 51, 0));
        Light.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Light", "Normal", "Extra", "Double", " " }));
        jPanel2.add(Light);
        Light.setBounds(115, 135, 110, 23);

        buttonGroup4.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 51, 0));
        jRadioButton7.setText("Robust Inspired Tomato Sauce");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton7);
        jRadioButton7.setBounds(295, 126, 217, 25);

        buttonGroup4.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 51, 0));
        jRadioButton8.setText("Heartly Marinara Sauce");
        jPanel2.add(jRadioButton8);
        jRadioButton8.setBounds(295, 176, 167, 25);

        buttonGroup4.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(255, 51, 0));
        jRadioButton9.setText("Alfredo Sauce");
        jPanel2.add(jRadioButton9);
        jRadioButton9.setBounds(295, 232, 111, 25);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Next");
        jPanel2.add(jButton2);
        jButton2.setBounds(840, 240, 81, 37);

        jTabbedPane1.addTab("Cheese And Sauce", jPanel2);

        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setText("Choose Toppings");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(45, 22, 197, 29);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Meats");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(45, 78, 46, 22);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 102, 0));
        jCheckBox1.setText("Chicken");
        jPanel3.add(jCheckBox1);
        jCheckBox1.setBounds(45, 118, 77, 25);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 51, 0));
        jCheckBox2.setText("Peperoni");
        jPanel3.add(jCheckBox2);
        jCheckBox2.setBounds(45, 161, 81, 25);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 51, 0));
        jCheckBox3.setText("Bacon");
        jPanel3.add(jCheckBox3);
        jCheckBox3.setBounds(45, 204, 67, 25);

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 51, 0));
        jCheckBox4.setText("Italian Sausage");
        jPanel3.add(jCheckBox4);
        jCheckBox4.setBounds(45, 247, 119, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 0));
        jLabel10.setText("Non-Meats");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(326, 78, 85, 22);

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 51, 0));
        jCheckBox5.setText("Onions");
        jPanel3.add(jCheckBox5);
        jCheckBox5.setBounds(326, 118, 71, 25);

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 51, 0));
        jCheckBox6.setText("Tomatoes");
        jPanel3.add(jCheckBox6);
        jCheckBox6.setBounds(326, 161, 89, 25);

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(255, 51, 0));
        jCheckBox7.setText("Peppers");
        jPanel3.add(jCheckBox7);
        jCheckBox7.setBounds(326, 204, 77, 25);

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(255, 51, 0));
        jCheckBox8.setText("Mushrooms");
        jPanel3.add(jCheckBox8);
        jCheckBox8.setBounds(326, 247, 99, 25);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Checkout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(810, 247, 129, 37);

        jTabbedPane1.addTab("Toppings", jPanel3);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Choose Your Crust :-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(42, 24, 352, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Choose Your Size");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(75, 81, 231, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Choose Your Crust");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(353, 81, 176, 25);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 51, 0));
        jRadioButton1.setText("Small");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(86, 130, 59, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 51, 0));
        jRadioButton2.setText("Medium");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(86, 183, 75, 25);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 51, 0));
        jRadioButton3.setText("Large");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(86, 244, 63, 25);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 51, 0));
        jRadioButton4.setText("Pan Pizza");
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(365, 130, 85, 25);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 51, 0));
        jRadioButton5.setText("Hand Made Thick");
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(365, 182, 133, 25);

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 51, 0));
        jRadioButton6.setText("Crunchy Thin");
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(365, 242, 111, 25);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(840, 250, 81, 37);

        jTabbedPane1.addTab("Size And Crust", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1032, 643));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            String query = "insert into tbl_pizza(size, crust, sauce, toppings, cheese) values (?, ?, ?, ?, ?)";
            PreparedStatement pst = dbc.conn.prepareStatement(query);
            if(jRadioButton1.isSelected()){
                size = "small";
            }else if(jRadioButton2.isSelected()){
                size = "Medium";
            }else if (jRadioButton3.isSelected()){
                size = "Large";
            }
            pst.setString(1, size);
            if(jRadioButton4.isSelected()){
                crust = "Pan Pizza";
            }else if(jRadioButton5.isSelected()){
                crust = "Hand Made Thick";
            }else if(jRadioButton6.isSelected()){
                crust = "Crunchy Thin";
            }
            pst.setString(2, crust);
            if(jRadioButton7.isSelected()){
                sauce = "Robust Inspired Tomato Sauce";
            }else if(jRadioButton8.isSelected()){
                sauce = "Heartly Marinara Sauce";
            }else if(jRadioButton9.isSelected()){
                sauce = "Alfredo Sauce";
            }
            pst.setString(3, sauce);
            String toppings = "";
            if(jCheckBox1.isSelected()){
                toppings+=jCheckBox1.getText()+" ";
            }
            if(jCheckBox2.isSelected()){
                toppings+=jCheckBox2.getText()+" ";
            }
            if(jCheckBox3.isSelected()){
                toppings+=jCheckBox3.getText()+" ";
            }
            if(jCheckBox4.isSelected()){
                toppings+=jCheckBox4.getText()+" ";
            }
            if(jCheckBox5.isSelected()){
                toppings+=jCheckBox5.getText()+" ";
            }
            if(jCheckBox6.isSelected()){
                toppings+=jCheckBox6.getText()+" ";
            }
            if(jCheckBox7.isSelected()){
                toppings+=jCheckBox7.getText()+" ";
            }
            if(jCheckBox8.isSelected()){
                toppings+=jCheckBox8.getText()+" ";
            }
            pst.setString(4, toppings);
            String cheese;
            cheese = Light.getSelectedItem().toString();
            pst.setString(5, cheese);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Added to checkout");
            setVisible(false);
            CheckOut checkOut  = new CheckOut();
            checkOut.setVisible(true);
                
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuildPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuildPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuildPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuildPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BuildPizza().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BuildPizza.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BuildPizza.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Light;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
